---
 - name: Download minikube
   get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp
    mode: '0777'

 - name: Copy minikube to /usr/local/bin/
   shell:
    cmd: cp /tmp/minikube-linux-amd64 /usr/local/bin/minikube && chmod 777 /usr/local/bin/minikube

 - name: Download kubectl
   get_url:
    url: https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
    dest: /tmp
    mode: '0777'

 - name: Copy kubectl to /usr/local/bin/
   shell:
    cmd: cp /tmp/kubectl /usr/local/bin/kubectl && chmod 777 /usr/local/bin/kubectl