---
  - name: initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
    args:
      chdir: /var/lib/jenkins
      creates: cluster_initialized.txt

  - name: create .kube directory
    become: yes
    file:
      path: /var/lib/jenkins/.kube
      state: directory
      owner: jenkins
      mode: 0755

  - name: copy admin.conf to user's kube config
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /var/lib/jenkins/.kube/config
      remote_src: yes
      owner: jenkins

  - name: install Pod network
    become: yes
    become_user: jenkins
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
    args:
      chdir: /var/lib/jenkins
      creates: pod_network_setup.txt# tasks file for k8smaster
      
  - name: Get the token for joining the worker nodes
    become: yes
    become_user: jenkins
    shell: kubeadm token create  --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

  # - debug:
  #   msg: "{{ kubernetes_join_command.stdout }}"

  - name: Copy join command to local file.
    become: yes
    local_action: copy content="{{ join_command_raw.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777