---
 - name: Add key
   apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

 - name: Ensure the repository is configured
   apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu focal stable 
        state: present

 - name:  Update cache
   apt:
        update_cache: yes
        state: latest

 - name: Install docker
   apt:
        name: docker-ce
        state: present

 - name: Start & Enable docker
   service: 
        name: docker
        state: started   
        
 - name: Create group docker 
   group:
     name: docker
     state: present

 - name:  add to group docker 
   ansible.builtin.user:
     name: jenkins
     groups: 
     - docker
     append: yes    
